name: NestJS API CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run e2e tests for NestJS with Mongoose
        run: docker compose -f docker-compose.document.ci.yaml --env-file env-example-document -p ci-document up --build --exit-code-from api
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Login docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: List images
        run: docker images
      - name: Build and push image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backendapptutor:v1 -f document.Dockerfile
          docker push ${{ secrets.DOCKER_USERNAME }}/backendapptutor:v1
